### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by DanielRuf** [bug-hunters/oas3-tools#13] opened 2019-12-01 23:01 UTC
3.0.2 is not supported in 1.0.2-RC2. See https://unpkg.com/browse/oas3-tools@1.0.2-RC2/lib/helpers.js (line 163).

**Comment by HugoMario** [comment] 2019-12-02 07:00
thanks for this catch!

**Comment by hkosova** [comment] 2020-02-17 08:27
Duplicate of #6.

**Closed** 2020-09-12 22:15 UTC
